font-size = 12
window-padding-x = 10
window-padding-y = 10
scrollback-limit = 20000000
copy-on-select = true
confirm-close-surface = false
shell-integration = detect
background-opacity = 0.85
cursor-style = block
mouse-hide-while-typing = true
